// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajrwyazsbsnuszwzxkuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcnd5YXpzYnNudXN6d3p4a3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzg0NTgsImV4cCI6MjA2ODgxNDQ1OH0.BM4ErQI0Yx4o-cIBSblpct3xd0jxOZCynC10LGmU5wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});